import ROOT
import math

path = "hists/combineyearsLoose_v5.3.1/testfake/"
fS = ROOT.TFile.Open(path+"signal.root")
#fS = ROOT.TFile.Open(path+"signal_private.root")
fP = ROOT.TFile.Open(path+"prompt.root")
fL = ROOT.TFile.Open(path+"lostlep.root")
fF = ROOT.TFile.Open(path+"fakes.root")
#fF = ROOT.TFile.Open(path+"ddfakes.root")
fQ = ROOT.TFile.Open(path+"qflip.root")
fG = ROOT.TFile.Open(path+"photon.root")


htemp= fF.Get("SRSSeeNsoftbVeto__ele_fake_ptcoretahist")
hSSeSRl = htemp.Clone("SSEle_preselection_tight")
htemp= fF.Get("SRSSemNsoftbVeto__ele_fake_ptcoretahist")
hSSeSRl.Add(htemp)
htemp= fF.Get("SRSS1JeeNsoftbVeto__ele_fake_ptcoretahist")
hSSeSRl.Add(htemp)
htemp= fF.Get("SRSS1JemNsoftbVeto__ele_fake_ptcoretahist")
hSSeSRl.Add(htemp)
htemp= fF.Get("SR0SFOSNsoftbVeto__ele_fake_ptcoretahist")
hSSeSRl.Add(htemp)

htemp= fF.Get("SRSSmmNsoftbVeto__muo_fake_ptcoretahist")
hSSmSRl = htemp.Clone("SSMuo_preselection_tight")
htemp= fF.Get("SRSSemNsoftbVeto__muo_fake_ptcoretahist")
hSSmSRl.Add(htemp)
htemp= fF.Get("SRSS1JmmNsoftbVeto__muo_fake_ptcoretahist")
hSSmSRl.Add(htemp)
htemp= fF.Get("SRSS1JemNsoftbVeto__muo_fake_ptcoretahist")
hSSmSRl.Add(htemp)
htemp= fF.Get("SR0SFOSNsoftbVeto__muo_fake_ptcoretahist")
hSSmSRl.Add(htemp)

htemp= fF.Get("SR1SFOSNsoftbVeto__ele_fake_ptcoretahist")
h3leSRl = htemp.Clone("ThreeLEle_preselection_tight")
htemp= fF.Get("SR2SFOSNsoftbVeto__ele_fake_ptcoretahist")
h3leSRl.Add(htemp)

htemp= fF.Get("SR1SFOSNsoftbVeto__muo_fake_ptcoretahist")
h3lmSRl = htemp.Clone("ThreeLMuo_preselection_tight")
htemp= fF.Get("SR2SFOSNsoftbVeto__muo_fake_ptcoretahist")
h3lmSRl.Add(htemp)

htemp= fF.Get("ARSSeeNsoftbVeto__ele_fake_ptcoretahist")
hSSeARl = htemp.Clone("SSEle_preselection_loose")
htemp= fF.Get("ARSSemNsoftbVeto__ele_fake_ptcoretahist")
hSSeARl.Add(htemp)
htemp= fF.Get("ARSS1JeeNsoftbVeto__ele_fake_ptcoretahist")
hSSeARl.Add(htemp)
htemp= fF.Get("ARSS1JemNsoftbVeto__ele_fake_ptcoretahist")
hSSeARl.Add(htemp)
htemp= fF.Get("AR0SFOSNsoftbVeto__ele_fake_ptcoretahist")
hSSeARl.Add(htemp)

htemp= fF.Get("ARSSmmNsoftbVeto__muo_fake_ptcoretahist")
hSSmARl = htemp.Clone("SSMuo_preselection_loose")
htemp= fF.Get("ARSSemNsoftbVeto__muo_fake_ptcoretahist")
hSSmARl.Add(htemp)
htemp= fF.Get("ARSS1JmmNsoftbVeto__muo_fake_ptcoretahist")
hSSmARl.Add(htemp)
htemp= fF.Get("ARSS1JemNsoftbVeto__muo_fake_ptcoretahist")
hSSmARl.Add(htemp)
htemp= fF.Get("AR0SFOSNsoftbVeto__muo_fake_ptcoretahist")
hSSmARl.Add(htemp)

htemp= fF.Get("AR1SFOSNsoftbVeto__ele_fake_ptcoretahist")
h3leARl = htemp.Clone("ThreeLEle_preselection_loose")
htemp= fF.Get("AR2SFOSNsoftbVeto__ele_fake_ptcoretahist")
h3leARl.Add(htemp)

htemp= fF.Get("AR1SFOSNsoftbVeto__muo_fake_ptcoretahist")
h3lmARl = htemp.Clone("ThreeLMuo_preselection_loose")
htemp= fF.Get("AR2SFOSNsoftbVeto__muo_fake_ptcoretahist")
h3lmARl.Add(htemp)


htemp= fF.Get("SRSSeeKinSel__ele_fake_ptcoretahist")
hSSeSRt = htemp.Clone("SSEle_fullselection_tight")
htemp= fF.Get("SRSSemKinSel__ele_fake_ptcoretahist")
hSSeSRt.Add(htemp)
htemp= fF.Get("SRSS1Jee1JKin__ele_fake_ptcoretahist")
hSSeSRt.Add(htemp)
htemp= fF.Get("SRSS1Jem1JKin__ele_fake_ptcoretahist")
hSSeSRt.Add(htemp)
htemp= fF.Get("SR0SFOSKinSel__ele_fake_ptcoretahist")
hSSeSRt.Add(htemp)

htemp= fF.Get("SRSSmmKinSel__muo_fake_ptcoretahist")
hSSmSRt = htemp.Clone("SSMuo_fullselection_tight")
htemp= fF.Get("SRSSemKinSel__muo_fake_ptcoretahist")
hSSmSRt.Add(htemp)
htemp= fF.Get("SRSS1Jmm1JKin__muo_fake_ptcoretahist")
hSSmSRt.Add(htemp)
htemp= fF.Get("SRSS1Jem1JKin__muo_fake_ptcoretahist")
hSSmSRt.Add(htemp)
htemp= fF.Get("SR0SFOSKinSel__muo_fake_ptcoretahist")
hSSmSRt.Add(htemp)

htemp= fF.Get("SR1SFOSKinSel__ele_fake_ptcoretahist")
h3leSRt = htemp.Clone("ThreeLEle_fullselection_tight")
htemp= fF.Get("SR2SFOSKinSel__ele_fake_ptcoretahist")
h3leSRt.Add(htemp)

htemp= fF.Get("SR1SFOSKinSel__muo_fake_ptcoretahist")
h3lmSRt = htemp.Clone("ThreeLMuo_fullselection_tight")
htemp= fF.Get("SR2SFOSKinSel__muo_fake_ptcoretahist")
h3lmSRt.Add(htemp)

htemp= fF.Get("ARSSeeKinSel__ele_fake_ptcoretahist")
hSSeARt = htemp.Clone("SSEle_fullselection_loose")
htemp= fF.Get("ARSSemKinSel__ele_fake_ptcoretahist")
hSSeARt.Add(htemp)
htemp= fF.Get("ARSS1Jee1JKin__ele_fake_ptcoretahist")
hSSeARt.Add(htemp)
htemp= fF.Get("ARSS1Jem1JKin__ele_fake_ptcoretahist")
hSSeARt.Add(htemp)
htemp= fF.Get("AR0SFOSKinSel__ele_fake_ptcoretahist")
hSSeARt.Add(htemp)

htemp= fF.Get("ARSSmmKinSel__muo_fake_ptcoretahist")
hSSmARt = htemp.Clone("SSMuo_fullselection_loose")
htemp= fF.Get("ARSSemKinSel__muo_fake_ptcoretahist")
hSSmARt.Add(htemp)
htemp= fF.Get("ARSS1Jmm1JKin__muo_fake_ptcoretahist")
hSSmARt.Add(htemp)
htemp= fF.Get("ARSS1Jem1JKin__muo_fake_ptcoretahist")
hSSmARt.Add(htemp)
htemp= fF.Get("AR0SFOSKinSel__muo_fake_ptcoretahist")
hSSmARt.Add(htemp)

htemp= fF.Get("AR1SFOSKinSel__ele_fake_ptcoretahist")
h3leARt = htemp.Clone("ThreeLEle_fullselection_loose")
htemp= fF.Get("AR2SFOSKinSel__ele_fake_ptcoretahist")
h3leARt.Add(htemp)

htemp= fF.Get("AR1SFOSKinSel__muo_fake_ptcoretahist")
h3lmARt = htemp.Clone("ThreeLMuo_fullselection_loose")
htemp= fF.Get("AR2SFOSKinSel__muo_fake_ptcoretahist")
h3lmARt.Add(htemp)


hSSFRel = hSSeSRl.Clone("FakeRate_SSEle_preselection")
hSSFRel.Divide(hSSeARl)
hSSFRml = hSSeSRl.Clone("FakeRate_SSMuo_preselection")
hSSFRml.Divide(hSSmARl)
hSSFRet = hSSeSRt.Clone("FakeRate_SSEle_fullselection")
hSSFRet.Divide(hSSeARt)
hSSFRmt = hSSeSRt.Clone("FakeRate_SSMuo_fullselection")
hSSFRmt.Divide(hSSmARt)
h3lFRel = h3leSRl.Clone("FakeRate_3lEle_preselection")
h3lFRel.Divide(h3leARl)
h3lFRml = h3leSRl.Clone("FakeRate_3lMuo_preselection")
h3lFRml.Divide(h3lmARl)
h3lFRet = h3leSRt.Clone("FakeRate_3lEle_fullselection")
h3lFRet.Divide(h3leARt)
h3lFRmt = h3leSRt.Clone("FakeRate_3lMuo_fullselection")
h3lFRmt.Divide(h3lmARt)

fout = ROOT.TFile("FakeRateFromWWWSR.root","recreate")
fout.cd()
hSSeSRl.Write()
hSSmSRl.Write()
h3leSRl.Write()
h3lmSRl.Write()
hSSeARl.Write()
hSSmARl.Write()
h3leARl.Write()
h3lmARl.Write()
hSSeSRt.Write()
hSSmSRt.Write()
h3leSRt.Write()
h3lmSRt.Write()
hSSeARt.Write()
hSSmARt.Write()
h3leARt.Write()
h3lmARt.Write()
hSSFRel.Write()
hSSFRml.Write()
hSSFRet.Write()
hSSFRmt.Write()
h3lFRel.Write()
h3lFRml.Write()
h3lFRet.Write()
h3lFRmt.Write()
fout.Close()
