
#python plot.py -i hists/Loose2018_v5.1.4/test2018_v5/ -P -s " 1" -1  -o plots2018quality -m -d -uw -w "ARSSeeFull,ARSSemFull,ARSSmmFull,ARSSSideeeFull,ARSSSideemFull,ARSSSidemmFull,AR0SFOSFull,AR1SFOSFull,AR2SFOSFull"
#python plot.py -i hists/Loose2017_v5.1.4/test2017_v5/ -P -s " 1" -1  -o plots2017quality -m -d -uw -w "ARSSeeFull,ARSSemFull,ARSSmmFull,ARSSSideeeFull,ARSSSideemFull,ARSSSidemmFull,AR0SFOSFull,AR1SFOSFull,AR2SFOSFull"

: <<'END'
python plot.py -i hists/combineyears_v5.2.0/new_v3/ -P -s " 1" -1  -o plots/combineyears_v5.2.0/plotsSRprenodata -m       -uw -w "SRSSeePreSel,SRSSemPreSel,SRSSmmPreSel,SRSSeePreSel,SRSSemPreSel,SRSSmmPreSel,SRSS1Jee1JPre,SRSS1Jem1JPre,SRSS1Jmm1JPre,SR0SFOSDYVeto,SR1SFOSDYVeto,SR2SFOSDYVeto"
#-v split signal
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOS__ele_relIso03EAXXMax  -n 20 -xt   "I^{max}_{rel}(e) -  0SFOS"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOS__muo_relIso03EAXXMax  -n 30 -xt   "I^{max}_{rel}(#mu) -  0SFOS"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSDYVeto__ele_relIso03EAXXMax  -n 20 -xt   "I^{max}_{rel}(e) -  0SFOS preselection"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSDYVeto__muo_relIso03EAXXMax  -n 30 -xt   "I^{max}_{rel}(#mu) -  0SFOS preselection"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSNsoftbVeto__ele_relIso03EAXXMax  -n 20 -xt   "I^{max}_{rel}(e) -  0SFOS, no soft-b"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSNsoftbVeto__muo_relIso03EAXXMax  -n 30 -xt   "I^{max}_{rel}(#mu) -  0SFOS, no soft-b"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSeem__ele_relIso03EAXXMax  -n 20 -xt   "I^{max}_{rel}(e) -  0SFOS (ee#mu)"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSeem__muo_relIso03EAXXMax  -n 30 -xt   "I^{max}_{rel}(#mu) -  0SFOS (ee#mu)"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSeemDYVeto__ele_relIso03EAXXMax  -n 20 -xt   "I^{max}_{rel}(e) -  0SFOS (ee#mu) preselection"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSeemDYVeto__muo_relIso03EAXXMax  -n 30 -xt   "I^{max}_{rel}(#mu) -  0SFOS (ee#mu) preselection"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSeemNsoftbVeto__ele_relIso03EAXXMax  -n 20 -xt   "I^{max}_{rel}(e) -  0SFOS (ee#mu), no soft-b"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSeemNsoftbVeto__muo_relIso03EAXXMax  -n 30 -xt   "I^{max}_{rel}(#mu) -  0SFOS (ee#mu), no soft-b"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSemm__ele_relIso03EAXXMax  -n 20 -xt   "I^{max}_{rel}(e) -  0SFOS (e#mu#mu)"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSemm__muo_relIso03EAXXMax  -n 30 -xt   "I^{max}_{rel}(#mu) -  0SFOS (e#mu#mu)"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSemmDYVeto__ele_relIso03EAXXMax  -n 20 -xt   "I^{max}_{rel}(e) -  0SFOS (e#mu#mu) preselection"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSemmDYVeto__muo_relIso03EAXXMax  -n 30 -xt   "I^{max}_{rel}(#mu) -  0SFOS (e#mu#mu) preselection"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSemmNsoftbVeto__ele_relIso03EAXXMax  -n 20 -xt   "I^{max}_{rel}(e) -  0SFOS (e#mu#mu), no soft-b"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSemmNsoftbVeto__muo_relIso03EAXXMax  -n 30 -xt   "I^{max}_{rel}(#mu) -  0SFOS (e#mu#mu), no soft-b"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR1SFOSDYVeto__ele_relIso03EAXXMax  -n 20 -xt   "I^{max}_{rel}(e) -  1SFOS preselection"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR1SFOSDYVeto__muo_relIso03EAXXMax  -n 30 -xt   "I^{max}_{rel}(#mu) -  1SFOS preselection"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR1SFOSNsoftbVeto__ele_relIso03EAXXMax  -n 20 -xt   "I^{max}_{rel}(e) -  1SFOS, no soft-b"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR1SFOSNsoftbVeto__muo_relIso03EAXXMax  -n 30 -xt   "I^{max}_{rel}(#mu) -  1SFOS, no soft-b"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SRSSem__ele_relIso03EAXXMax  -n 20 -xt   "I^{max}_{rel}(e) -  SS e#mu"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SRSSem__muo_relIso03EAXXMax  -n 30 -xt   "I^{max}_{rel}(#mu) -  SS e#mu"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SRSSemPreSel__ele_relIso03EAXXMax  -n 20 -xt   "I^{max}_{rel}(e) -  SS e#mu #geq2j preselection"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SRSSemPreSel__muo_relIso03EAXXMax  -n 30 -xt   "I^{max}_{rel}(#mu) -  SS e#mu #geq2j preselection"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SRSSemNsoftbVeto__ele_relIso03EAXXMax  -n 20 -xt   "I^{max}_{rel}(e) -  SS e#mu #geq2j, no soft-b"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SRSSemNsoftbVeto__muo_relIso03EAXXMax  -n 30 -xt   "I^{max}_{rel}(#mu) -  SS e#mu #geq2j, no soft-b"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SRSSmm__muo_relIso03EAXXMax  -n 30 -xt   "I^{max}_{rel}(#mu) -  SS #mu#mu"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SRSSmmPreSel__muo_relIso03EAXXMax  -n 30 -xt   "I^{max}_{rel}(#mu) -  SS #mu#mu #geq2j preselection"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SRSSmmNsoftbVeto__muo_relIso03EAXXMax  -n 30 -xt   "I^{max}_{rel}(#mu) -  SS #mu#mu #geq2j, no soft-b"

python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSDYVeto__Mllmin -v -n 15 -xt   "m^{min}_{ll} -  0SFOS preselection"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSDYVeto__mOS_near -v  -n 15 -xt   "m^{near-Z}_{OS} -  0SFOS preselection"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSDYVeto__mOS_far -v  -n 15 -xt   "m^{far-Z}_{OS} -  0SFOS preselection"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSKinSel__Mllmin -v  -n 15 -xt   "m^{min}_{ll} -  0SFOS kin.selection"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSKinSel__mOS_near -v  -n 15 -xt   "m^{near-Z}_{OS} -  0SFOS kin.selection"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSKinSel__mOS_far -v  -n 15 -xt   "m^{far-Z}_{OS} -  0SFOS kin.selection"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR1SFOSKinSel__Mllmin -v  -n 15 -xt   "m^{min}_{ll} -  1SFOS kin.selection"

python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOSDYVeto__nbsoft  -n 5 -xt   "n_{soft-b} -  0SFOS preselection"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR1SFOSDYVeto__nbsoft  -n 5 -xt   "n_{soft-b} -  1SFOS preselection"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SRSSemPreSel__nbsoft  -n 5 -xt   "n_{soft-b} -  SS e#mu #geq2j preselection"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SRSSemPreSel__nbsoft  -n 5 -xt   "n_{soft-b} -  SS #mu#mu #geq2j preselection"

python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR0SFOS__nb  -n 5 -xt   "n_{b} -  0SFOS"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SR1SFOS__nb  -n 5 -xt   "n_{b} -  1SFOS"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SRSSem__nb  -n 5 -xt   "n_{b} -  SS e#mu"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SRSSmm__nb  -n 5 -xt   "n_{b} -  SS #mu#mu"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SRSSem__nbsoft  -n 5 -xt   "n_{soft-b} -  SS e#mu"
python ./plot.py -i hists/combineyears_v5.3.0/newIsolation/ -m SRSSmm__nbsoft  -n 5 -xt   "n_{soft-b} -  SS #mu#mu"
END
: <<'END'
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR0SFOSDYVeto__lep_pt0  -n 20 -xt   "l0-pt -  0SFOS preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR0SFOSDYVeto__lep_pt1  -n 20 -xt   "l1-pt -  0SFOS preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR0SFOSDYVeto__lep_pt2  -n 20 -xt   "l2-pt -  0SFOS preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR1SFOSDYVeto__lep_pt0  -n 20 -xt   "l0-pt -  1SFOS preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR1SFOSDYVeto__lep_pt1  -n 20 -xt   "l1-pt -  1SFOS preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR1SFOSDYVeto__lep_pt2  -n 20 -xt   "l2-pt -  1SFOS preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR2SFOSDYVeto__lep_pt0  -n 20 -xt   "l0-pt -  2SFOS preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR2SFOSDYVeto__lep_pt1  -n 20 -xt   "l1-pt -  2SFOS preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR2SFOSDYVeto__lep_pt2  -n 20 -xt   "l2-pt -  2SFOS preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR0SFOSKinSel__lep_pt0  -n 20 -xt   "l0-pt -  0SFOS full selection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR0SFOSKinSel__lep_pt1  -n 20 -xt   "l1-pt -  0SFOS full selection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR0SFOSKinSel__lep_pt2  -n 20 -xt   "l2-pt -  0SFOS full selection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR1SFOSKinSel__lep_pt0  -n 20 -xt   "l0-pt -  1SFOS full selection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR1SFOSKinSel__lep_pt1  -n 20 -xt   "l1-pt -  1SFOS full selection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR1SFOSKinSel__lep_pt2  -n 20 -xt   "l2-pt -  1SFOS full selection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR2SFOSKinSel__lep_pt0  -n 20 -xt   "l0-pt -  2SFOS full selection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR2SFOSKinSel__lep_pt1  -n 20 -xt   "l1-pt -  2SFOS full selection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR2SFOSKinSel__lep_pt2  -n 20 -xt   "l2-pt -  2SFOS full selection"

python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR0SFOSDYVeto__METWide  -n 20 -xt   "pTMiss -  0SFOS preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR1SFOSDYVeto__METWide  -n 20 -xt   "pTMiss -  1SFOS preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR2SFOSDYVeto__METWide  -n 20 -xt   "pTMiss -  2SFOS preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR0SFOSKinSel__METWide  -n 20 -xt   "pTMiss -  0SFOS full selection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR1SFOSKinSel__METWide  -n 20 -xt   "pTMiss -  1SFOS full selection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR2SFOSKinSel__METWide  -n 20 -xt   "pTMiss -  2SFOS full selection"

python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR0SFOSDYVeto__nj30  -n 5 -xt   "nJ -  0SFOS preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR1SFOSDYVeto__nj30  -n 5 -xt   "nJ -  1SFOS preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR2SFOSDYVeto__nj30  -n 5 -xt   "nJ -  2SFOS preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR0SFOSKinSel__nj30  -n 5 -xt   "nJ -  0SFOS full selection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR1SFOSKinSel__nj30  -n 5 -xt   "nJ -  1SFOS full selection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testmaster/ -m SR2SFOSKinSel__nj30  -n 5 -xt   "nJ -  2SFOS full selection"
END
: <<'END'
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testfake/ -m SR0SFOSDYVeto__ele_fake_ptcoretahist  -n 12 -xt   "elefake -  0SFOS SR preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testfake/ -m SR0SFOSDYVeto__muo_fake_ptcoretahist  -n 12 -xt   "muofake -  0SFOS SR preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testfake/ -m SR0SFOSKinSel__ele_fake_ptcoretahist  -n 12 -xt   "elefake -  0SFOS SR full selection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testfake/ -m SR0SFOSKinSel__muo_fake_ptcoretahist  -n 12 -xt   "muofake -  0SFOS SR full selection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testfake/ -m AR0SFOSDYVeto__ele_fake_ptcoretahist  -n 12 -xt   "elefake -  0SFOS AR preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testfake/ -m AR0SFOSDYVeto__muo_fake_ptcoretahist  -n 12 -xt   "muofake -  0SFOS AR preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testfake/ -m AR0SFOSKinSel__ele_fake_ptcoretahist  -n 12 -xt   "elefake -  0SFOS AR full selection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testfake/ -m AR0SFOSKinSel__muo_fake_ptcoretahist  -n 12 -xt   "muofake -  0SFOS AR full selection"

python ./plot.py -i hists/combineyearsLoose_v5.3.1/testfake/ -m SRSSemPreSel__ele_fake_ptcoretahist  -n 12 -xt   "elefake -  0SFOS SR preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testfake/ -m SRSSemPreSel__muo_fake_ptcoretahist  -n 12 -xt   "muofake -  0SFOS SR preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testfake/ -m SRSSemKinSel__ele_fake_ptcoretahist  -n 12 -xt   "elefake -  0SFOS SR full selection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testfake/ -m SRSSemKinSel__muo_fake_ptcoretahist  -n 12 -xt   "muofake -  0SFOS SR full selection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testfake/ -m ARSSemPreSel__ele_fake_ptcoretahist  -n 12 -xt   "elefake -  0SFOS AR preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testfake/ -m ARSSemPreSel__muo_fake_ptcoretahist  -n 12 -xt   "muofake -  0SFOS AR preselection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testfake/ -m ARSSemKinSel__ele_fake_ptcoretahist  -n 12 -xt   "elefake -  0SFOS AR full selection"
python ./plot.py -i hists/combineyearsLoose_v5.3.1/testfake/ -m ARSSemKinSel__muo_fake_ptcoretahist  -n 12 -xt   "muofake -  0SFOS AR full selection"
END

./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m GammaCRLowMT__DPhi3lMET     -d -n 30 -xt "#Delta#phi(lll,p_{T}^{miss}) | #gamma CR, inverted m_{T}^{max/3rd}"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m GammaCRLowMT__METWide       -d -n 30 -xt "p_{T}^{miss} [GeV] | #gamma CR, inverted m_{T}^{max/3rd}"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m GammaCRLowMT__Pt3l          -d -n 30 -xt "p_{T}(lll) [GeV] | #gamma CR, inverted m_{T}^{max/3rd}"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m GammaCRLowMT__M3l           -d -n 30 -xt "m_{lll} [GeV] | #gamma CR, inverted m_{T}^{max/3rd}"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m GammaCRLowPt3l__DPhi3lMET   -d -n 30 -xt "#Delta#phi(lll,p_{T}^{miss}) | #gamma CR, inverted p_{T}(lll)"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m GammaCRLowPt3l__METWide     -d -n 30 -xt "p_{T}^{miss} [GeV] | #gamma CR, inverted p_{T}(lll)"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m GammaCRLowPt3l__MTmax       -d -n 30 -xt "m_{T}^{max} [GeV] | #gamma CR, inverted p_{T}(lll)"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m GammaCRLowPt3l__MT3rd       -d -n 30 -xt "m_{T}^{3rd} [GeV] | #gamma CR, inverted p_{T}(lll)"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m GammaCRLowPt3l__M3l         -d -n 30 -xt "m_{lll} [GeV] | #gamma CR, inverted p_{T}(lll)"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m GammaCRLowPt3lMT__DPhi3lMET -d -n 30 -xt "#Delta#phi(lll,p_{T}^{miss}) | #gamma CR, inverted m_{T}^{max/3rd}+p_{T}(lll)"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m GammaCRLowPt3lMT__METWide   -d -n 30 -xt "p_{T}^{miss} [GeV] | #gamma CR, inverted m_{T}^{max/3rd}+p_{T}(lll)"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m GammaCRLowPt3lMT__M3l       -d -n 30 -xt "m_{lll} [GeV] | #gamma CR, inverted m_{T}^{max/3rd}+p_{T}(lll)"

./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m WWVBSVRHighMJJ__DetajjL  -7 -d -n 30 -xt "#Delta#eta_{JJ} | WW VBS VR"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m WWVBSVRHighMJJ__METWide  -7 -d -n 30 -xt "p_{T}^{miss} [GeV] | WW VBS VR (only inverted m_{JJ})"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m WWVBSVRHighDEta__MjjL    -7 -d -n 30 -xt "m_{JJ} [GeV] | WW VBS VR"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m WWVBSVRHighDEta__METWide -7 -d -n 30 -xt "p_{T}^{miss} [GeV] | WW VBS VR (only inverted #Delta#eta_{JJ})"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m WWVBSVR__DetajjL         -7 -d -n 30 -xt "#Delta#eta_{JJ} | WW VBS VR"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m WWVBSVR__MjjL            -7 -d -n 30 -xt "m_{JJ} [GeV] | WW VBS VR"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m WWVBSVR__METWide         -7 -d -n 30 -xt "p_{T}^{miss} [GeV] | WW VBS VR"

./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m ttWVRlNBgeq1__nb         -7 -d -n 5 -xt "n_{b}(loose) | ttV VR (n_{b}(loose)#geq1"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m ttWVRmNBgeq1__nb         -7 -d -n 5 -xt "n_{b}(loose) | ttV VR (n_{b}(medium)#geq1"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m ttWVRlNBgeq2__nb         -7 -d -n 5 -xt "n_{b}(loose) | ttV VR (n_{b}(loose)#geq2"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m ttWVRmNBgeq2__nb         -7 -d -n 5 -xt "n_{b}(loose) | ttV VR (n_{b}(medium)#geq2"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m ttZWZfitRegion__nb       -7 -d -n 5 -xt "n_{b}(loose) | ttZ vs. WZ fit region"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m ttWVRlNBgeq1__nj30       -7 -d -n 7 -xt "n_{j} | ttV VR (n_{b}(loose)#geq1"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m ttWVRmNBgeq1__nj30       -7 -d -n 7 -xt "n_{j} | ttV VR (n_{b}(medium)#geq1"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m ttWVRlNBgeq2__nj30       -7 -d -n 7 -xt "n_{j} | ttV VR (n_{b}(loose)#geq2"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m ttWVRmNBgeq2__nj30       -7 -d -n 7 -xt "n_{j} | ttV VR (n_{b}(medium)#geq2"

./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m WZCRSSnoZmassLowDetaMjj__MllOnOff      -d -n 30 -xt "m_{SFOS} [GeV] | SS-2j WZ CR, preselection"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m WZCRSSnoZmassLowDetaMjj__Mjj           -d -n 30 -xt "m_{jj} [GeV] | SS-2j WZ CR, preselection"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m WZCRSSnoZmassKinSel__MllOnOff          -d -n 30 -xt "m_{SFOS} [GeV] | SS-2j WZ CR"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m WZCRSSnoZmassKinSel__Mjj               -d -n 30 -xt "m_{jj} [GeV] | SS-2j WZ CR"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m WZCRSS1JnoZcandNsoftbVeto__MllOnOff    -d -n 30 -xt "m_{SFOS} [GeV] | SS-1j WZ CR, preselection"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m WZCRSS1JnoZcand1JKin__MllOnOff         -d -n 30 -xt "m_{SFOS} [GeV] | SS-1j WZ CR"

./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m WZCR3LnoZmassKinSelInvertOne__MllOnOff   -d -n 30 -xt "m_{SFOS} [GeV] | 3l WZ VR, inverted sideband (any)"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m WZCR3LnoZmassKinSelInvertMTmax__MllOnOff -d -n 30 -xt "m_{SFOS} [GeV] | 3l WZ VR, inverted sideband (m_{T}^{max/3rd})"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m WZCR3LnoZmassKinSelInvertDPhi__MllOnOff  -d -n 30 -xt "m_{SFOS} [GeV] | 3l WZ VR, inverted sideband (#Delta#phi(lll,p_{T}^{miss}))"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m WZCR3LnoZmassKinSelInvertPt3l__MllOnOff  -d -n 30 -xt "m_{SFOS} [GeV] | 3l WZ VR, inverted sideband (p_{T}(lll))"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m WZCR3LnoZmassKinSelInvertAll__MllOnOff   -d -n 30 -xt "m_{SFOS} [GeV] | 3l WZ VR, inverted sideband (all)"

./plot.py -i hists/combineyearsLoose_v5.3.2/master/
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m WZCR1SFOSPreSel__nj30  -d -n 7 -xt "n_{j} | 1 SFOS WZ CR preselection"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m SR1SFOSPreSel__nj30       -n 7 -xt "n_{j} | 1 SFOS SR preselection"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m SRSSmmKinSel__nj30        -n 7 -xt "n_{j} | #mu^{#pm}#mu^{#mp} SR"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/ -m WZCRSSmmKinSel__nj30   -d -n 7 -xt "n_{j} | #mu^{#pm}#mu^{#mp} WZ CR"
./plot.py -i hists/combineyearsLoose_v5.3.2/master/  -o plots/combineyearsLoose_v5.3.2/masterX -m -d      -uw -w "WZCRSSeeMjjInFull,WZCRSSemMjjInFull,WZCRSSmmMjjInFull,WZCRSSeeMjjOutFull,WZCRSSemMjjOutFull,WZCRSSmmMjjOutFull,WZCRSS1JeeFull,WZCRSS1JemFull,WZCRSS1JmmFull,WZCR0SFOSFull,WZCR1SFOSFull,WZCR2SFOSFull"
